- LCLS-II/core/rtl/GthRxAlignCheck.vhd
SLV range bug fix  (required for Vivado 2017.3)
> Pre release lcls2

- LCLS-II/evr/rtl/EvrV2Pkg.vhd
- LCLS-II/evr/rtl/EvrV2Trigger.vhd
fixed the synthesis error of 'width mismatch in assignment; target has 28 bits, source has 19 bits', which doesn't show up in Vivado 2016.4 but does in Vivado 2017.1 (or later)
> ESLTIMING-15

- LCLS-II/evr/rtl/EvrV2CoreTriggers.vhd
```
Hi Larry,
Could you, please, bring option to set this parameter, TRIG_DEPTH_C, to the level settable by application in next release.
This way application can pipeline trigger without dropping them as with setting to 0 if required trigger delay will be more then inter-clock spacing.
It is not issue now since 1 uSec relatively long time  but with real environment when different channels may need to have different delays it could become issue .
So, at least application at that point can select setting this option and go to Advanced core.
Leonid  
```
> adding TRIG_PIPE_G generic

- yaml/TPGControl.yaml
CPSW requires all WO variables to be 32-bit size and 32-bit aligned
> v1.11.3 release candidate

- LCLS-II/core/rtl/TimingCore.vhd
It seems that the NO_GEN_ASYNC generate statement should drive appTimingBus_i instead of appTimingBus. There is no problem if ASYNC_G is TRUE.
> Fix for ESLCOMMON-220; appTimingBus has multiple drivers if ASYNC_G is FALSE

- .lfsconfig
A while ago an '.lfsconfig' file was erroneously pushed. This was meant for local use only.
> ESLCOMMON-234

- LCLS-II/core/rtl/TimingDeserializer.vhd
- LCLS-II/core/rtl/TimingSerializer.vhd
- LCLS-II/core/rtl/TimingStreamTx.vhd
The combinatorial code in these modules contained a bug which renders
the reset signal ineffective.
See [jira ticket](https://jira.slac.stanford.edu/browse/ESLTIMING-22)
> Reset ignored by TimingSerializer, TimingDeserializer, TimingStreamTx

- LCLS-II/core/rtl/BsaControl.vhd
- LCLS-II/core/rtl/BsaControlv2.vhd
- LCLS-II/core/rtl/ClockTime.vhd
- LCLS-II/core/rtl/ClockTime_186MHz.vhd
- LCLS-II/core/rtl/CtrControl.vhd
- LCLS-II/core/rtl/Divider.vhd
- LCLS-II/core/rtl/EventSelect.vhd
- LCLS-II/core/rtl/TPFifo.vhd
- LCLS-II/core/rtl/TPGMini.vhd
- LCLS-II/core/rtl/TPGMiniStream.vhd
- LCLS-II/core/rtl/TPGNotify.vhd
- LCLS-II/core/rtl/TPSerializer.vhd
- LCLS-II/core/rtl/TimingDeserializer.vhd
- LCLS-II/core/rtl/TimingSerialDelay.vhd
- LCLS-II/core/rtl/TimingSerializer.vhd
- LCLS-II/core/rtl/TimingStreamTx.vhd
- LCLS-II/core/rtl/WordSerializer.vhd
- LCLS-II/evr/rtl/EvrV2EventSelect.vhd
- LCLS-II/evr/rtl/EvrV2FromV1.vhd
- LCLS-II/evr/rtl/EvrV2Trigger.vhd
- As part of the refactoring, removed all use of `use work.all;`
> remove use work.all;

- ruckus.tcl
Require surf v2.0.6 or later and ruckus v2.1.2 or later
> Update submodule locks

- ruckus.tcl
- Check for Vivado version 2019.1 (or later)
- Update submodule locks #96
> v2.0.1 Release Candidate

- LCLS-II/core/rtl/TimingCore.vhd
- updating TimingCore.obEthMsgSlave default to AXI_STREAM_SLAVE_FORCE_C
- updating TimingCore.ETHMSG_AXIS_CFG_G default to EMAC_AXIS_CONFIG_C
> Generic/Port Default Updates

- LCLS-II/core/rtl/TPGMiniStream.vhd
- LCLS-II/core/rtl/TPGPkg.vhd
Update LCLS1 timing emulation to generate beam on 71kHz boundaries like the real system.  Add holdoff and count registers to TPG fault control and status record types.
> Tpg beamdiag

- LCLS-II/evr/rtl/EvrV2CoreTriggers.vhd
- LCLS-II/evr/rtl/EvrV2EventSelect.vhd
- LCLS-II/evr/rtl/EvrV2FromV1.vhd
- python/LclsTimingCore/EvrV2ChannelReg.py
- In `EvrV2ChannelReg.py`
- Split RateType field from RateSel register variable
- Split DestType field from DestSel register variable
- **This might mess up some existing config files?**
- Add default signal assignments so that registers have an initial value in simulation.
> Software and simulation enhancements

- LCLS-II/core/rtl/TimingCore.vhd
- python/LclsTimingCore/TimingFrameRx.py
- setting ModeSel.verify = False
- No verification because axilR.modeSelEn=0x0 can overwrite ModeSel with ClkSel
- TimingCore AXI-Lite bus init terminations
> TimingFrameRx.py Bug Fix and TimingCore.vhd Update

- LCLS-II/evr/rtl/EvrV2Pkg.vhd
- Default to 1 cycle width, 0 will default channel
> updating EvrV2Pkg.EVRV2_TRIGGER_CONFIG_INIT_C.width default from 0x0 to 0x1

- LCLS-I/evr/EvrV1EventReceiver.vhd
This removes from the trigger logic a reset that occurs every 360 Hz fiducial.  In the MRF design, this reset was not intended for the trigger logic but for a prescaler on special frequency outputs.
> Remove prescaler reset from LCLS-I evr trigger logic

- LCLS-II/core/rtl/TimingCore.vhd
- LCLS-II/evr/rtl/EvrV2TrigReg.vhd
- yaml/EvrV2TriggerReg.yaml
- Fix yaml for Complementary trigger bits
- Update trigger registers to current axi-lite macros
- Add delayTap readback register to yaml
- Add missing modeSelApp output to TimingCore
- Only the EvrCardG2 project uses the complementary triggers and delayTap.  
- lcls-ued-llrf might use the complementary triggers soon.
> v3.4.2 release candidate

- LCLS-II/core/rtl/BsaControlv2.vhd
- LCLS-II/core/rtl/TPGMini.vhd
Make an explicit signal interface for the BSA timeout.  It's currently wrong in production, but no one really noticed.
> V3.6.3 bsarate

- LCLS-II/gtyUltraScale+/rtl/TimingGtCoreWrapper.vhd
The `gtyUltrascle+/TimingGtCoreWrapper` module was using `Gthe3ChannelDummy` instead of `Gtye4ChannelDummy`.
But `Gthe3ChannelDummy` doesn't even get loaded by ruckus for ultrascale+ designs.
This is now fixed.
> Use Gtye4ChannelDummy in gtyUltrascale+ core wrapper

- LCLS-II/core/rtl/GthRxAlignCheck.vhd
- LCLS-II/core/rtl/TimingDeserializer.vhd
- LCLS-II/core/rtl/TimingFrameRx.vhd
- LCLS-II/core/rtl/TimingRx.vhd
- LCLS-II/gthUltraScale+/coregen/TimingGth_extref.dcp
- LCLS-II/gthUltraScale+/coregen/TimingGth_extref.xci
- LCLS-II/gthUltraScale+/coregen/TimingGth_fixedlat.dcp
- LCLS-II/gthUltraScale+/coregen/TimingGth_fixedlat.xci
- LCLS-II/gthUltraScale+/rtl/TimingGthCoreWrapper.vhd
- LCLS-II/gthUltraScale+/ruckus.tcl
- python/LclsTimingCore/GthRxAlignCheck.py
Fixes a reset scheme issue on the GTH Rx alignment process
> Fix Rx issues

- LCLS-II/core/rtl/TPGPkg.vhd
- LCLS-II/core/rtl/TimingStreamTx.vhd
- [Modify TimingStreamTx to be consistent with EVG output. EVRs can tell the difference](https://github.com/slaclab/lcls-timing-core/pull/164/commits/a845efa70ec3bc572107734ba8fec2e3911b8a41) 
- [Add AC sampling configuration registers](https://github.com/slaclab/lcls-timing-core/pull/164/commits/e61afd4205393ccaa531bf7adb17063e60a0db12)
> V3.7.0 streamtx evr

- LCLS-II/core/rtl/TPGPkg.vhd
- LCLS-II/core/rtl/TimingDeserializer.vhd
- LCLS-II/core/rtl/TimingFrameRx.vhd
- LCLS-II/core/rtl/TimingRx.vhd
- LCLS-II/core/rtl/TimingStreamTx.vhd
- LCLS-II/gthUltraScale+/rtl/TimingGthCoreWrapper.vhd
- conda-recipe/build.sh
- generateDocumentationAndDeploy.sh
- [whitespace clean up](https://github.com/slaclab/lcls-timing-core/commit/3b83ea2587df9ebd5501e02774debe2069104990)
- #164
> Release Candidate v3.8.1

- LCLS-II/core/rtl/TPGMini.vhd
Added ports: "steps, remainder, divisor" to ClockTime.vhd
> added ClockTime ports

- LCLS-II/gtx7/rtl/TimingGtCoreWrapper.vhd
- Updating the RX RX_EQUALIZER_G from `DFE` to `LPM` (only impacts GTX7 FPGAs)
- Related to https://github.com/slaclab/evr-card-g2/pull/11
> Release Candidate v3.8.3

- LCLS-II/core/rtl/TimingGthWrapper.vhd
- LCLS-II/gthUltraScale+/rtl/TimingGthCoreWrapper.vhd
- LCLS-II/gthUltraScale/rtl/TimingGtCoreWrapper.vhd
- LCLS-II/gtyUltraScale+/rtl/TimingGtCoreWrapper.vhd
- StableClk (which is GT's drpClk) in the IP core configured for 156.25MHz/2 (78.125MHz)
> Updating code comments for Ultrascale/Ultrascale+ GTs wrapper

- LCLS-II/gthUltraScale+/ruckus.tcl
- LCLS-II/gthUltraScale/ruckus.tcl
- LCLS-II/gtyUltraScale+/ruckus.tcl
The ruckus.tcl files that load IP cores now look for an `LCLS_TIMING_XCI` environment variable.
If it is set to 1, then the XCI file is loaded instead of the DCP.
This is useful in simulation. For example, add this line to the target makefile so that the XCI is loaded when building the project for VCS simulation.
```Makefile
vcs: export LCLS_TIMING_XCI=1
```
> Add Ruckus Flag to Load XCI Instead of DCP

- LCLS-II/evr/rtl/EvrV2Trigger.vhd
I fixed a long standing problem (and a newly discovered one) where changing the trigger configuration parameters, namely delay and width, while the trigger pipeline is enabled causes errors that can overflow the pipeline (negative delay change) or produce the wrong delay (width change).
The one cycle push of delay onto the fifo was replaced with two pushes, each representing a transition of the output trigger state.
> V3.8.3 trigger pipeline fix

- LCLS-II/core/rtl/TimingGthWrapper.vhd
- LCLS-II/evr/rtl/EvrV2Trigger.vhd
- LCLS-II/gthUltraScale+/rtl/TimingGthCoreWrapper.vhd
- LCLS-II/gthUltraScale+/ruckus.tcl
- LCLS-II/gthUltraScale/rtl/TimingGtCoreWrapper.vhd
- LCLS-II/gthUltraScale/ruckus.tcl
- LCLS-II/gtyUltraScale+/rtl/TimingGtCoreWrapper.vhd
- LCLS-II/gtyUltraScale+/ruckus.tcl
> Release Candidate v3.8.4

- LCLS-II/evr/rtl/EvrV2Trigger.vhd
- LCLS-II/gthUltraScale+/rtl/TimingGthCoreWrapper.vhd
- LCLS-II/gthUltraScale/rtl/TimingGtCoreWrapper.vhd
- LCLS-II/gtyUltraScale+/rtl/TimingGtCoreWrapper.vhd
- [migrating from lcls_timing_core.GthRxAlignCheck to surf.GtRxAlignCheck](https://github.com/slaclab/lcls-timing-core/commit/9122f5ba289285c4f3f9890745d136894df68cbd)
- [Remove NO_FIFO implementation from EvrV2Trigger; its always needed.](https://github.com/slaclab/lcls-timing-core/commit/0ecfc2f92aec08e4bfe5a2ab52447d815f46a826)
> Release Candidate v3.10.0

- LCLS-II/core/rtl/TimingSerialDelay.vhd
Release candidate v3.10.2.  Recoding of TimingSerialDelay.vhd to put all the combinational logic into the process and use a single synchronous FIFO rather than 2 separately controlled FIFOs.  This fixes a problem with the extension streams slipping by one or more frames compared to the core timing stream during outages/recovery.
> Release candidate v3.10.2.
