- LCLS-II/core/rtl/TPGMiniReg.vhd
- yaml/TPGMiniCore.yaml
Here's what I'm planning.  Building the test now.
> Changed WO registers to RW, some with new address offsets

- LCLS-II/core/rtl/TPGMini.vhd
- LCLS-II/core/rtl/TPGMiniReg.vhd
- yaml/TPGMiniCore.yaml
Changed the register mapping to separate noncacheable fields into their own independent accesses.
[ESLCOMMON-211](https://jira.slac.stanford.edu/browse/ESLCOMMON-211)
> Make TPGMini vhd and yaml compatible with controlGui

- python/LclsTimingCore/TPGMiniCore.py
python update for overlapping variables
[ESCRYODET-116](https://jira.slac.stanford.edu/browse/ESCRYODET-116)
> v1.11.4 release candidate

- LCLS-II/gthUltraScale+/coregen/TimingGth_extref.dcp
- LCLS-II/gthUltraScale+/coregen/TimingGth_fixedlat.dcp
- LCLS-II/gthUltraScale+/coregen/TimingGth_fixedlat.xci
- LCLS-II/gthUltraScale+/rtl/TimingGtCoreWrapper.vhd
- LCLS-II/gthUltraScale+/ruckus.tcl
- LCLS-II/gthUltraScale/rtl/TimingGtCoreWrapper.vhd
- LCLS-II/gtyUltraScale+/coregen/TimingGty_extref.dcp
- LCLS-II/gtyUltraScale+/coregen/TimingGty_extref.xci
- LCLS-II/gtyUltraScale+/coregen/TimingGty_fixedlat.dcp
- LCLS-II/gtyUltraScale+/coregen/TimingGty_fixedlat.xci
- LCLS-II/gtyUltraScale+/rtl/TimingGtCoreWrapper.vhd
- LCLS-II/gtyUltraScale+/ruckus.tcl
- LCLS-II/ruckus.tcl
- python/LclsTimingCore/TimingFrameRx.py
1. updating for the new ultrascale+ GT remap
2. adding back RxPllReset python variable
> v1.11.5 release candidate

- LCLS-II/core/rtl/TimingCore.vhd
- LCLS-II/core/rtl/TimingFrameRx.vhd
- LCLS-II/core/rtl/TimingPkg.vhd
- LCLS-II/core/rtl/TimingRx.vhd
- LCLS-II/core/rtl/default/TimingExtnPkg.vhd
- LCLS-II/evr/rtl/EvrV2CorePulseGen.vhd
- LCLS-II/evr/rtl/EvrV2CoreTriggers.vhd
- LCLS-II/evr/rtl/EvrV2EventSelect.vhd
- LCLS-II/evr/rtl/EvrV2Module.vhd
- ruckus.tcl
Remove references to ExptBusType.  Add references to timingExtn.
> V1.11.6 timingextn

- LCLS-II/core/rtl/GthRxAlignCheck.vhd
- releaseNotes.py
- ruckus.tcl
> v1.12.3 release candidate

- LCLS-II/gthUltraScale/rtl/TimingGtCoreWrapper.vhd
- python/LclsTimingCore/__init__.py
- ruckus.tcl
- updating submodule locks 
- python updates
- exposing AxiLiteConfig addrBits and DRP offset as generics in  LCLS-II/gthUltraScale/rtl/TimingGtCoreWrapper.vhd
> v1.12.5 release candidate

- LCLS-I/evr/EvrV1CoreIsrCtrl.vhd
- LCLS-I/evr/EvrV1CoreIsrCtrl.vhd bug fix
> LCLS-I/evr/EvrV1CoreIsrCtrl.vhd bug fix

- LCLS-II/core/rtl/TimingMsgDelay.vhd
> TimingMsgDelay.vhd bug fix

- LCLS-II/evr/rtl/EvrV2CorePulseGen.vhd
Remove the remainder of partitionAddr signal from interfaces.
> Partition addr removal

- LCLS-II/gtx7/rtl/TimingGtCoreWrapper.vhd
- LCLS-II/gtx7/ruckus.tcl
- LCLS-II/ruckus.tcl
- Used with Kintex-7 FPGAs
- Mostly copied from https://github.com/slaclab/evr-card-g2/blob/b48a33be9147a493835a52f29a620d6e3882bebe/firmware/common/EvrCardG2/general/rtl/EvrCardG2Gtx.vhd
> adding gtx7/TimingGtCoreWrapper

- LCLS-I/evr/EvrV1CoreIsrCtrl.vhd
- LCLS-II/core/rtl/BsaControl.vhd
- LCLS-II/core/rtl/BsaControlv2.vhd
- LCLS-II/core/rtl/CtrControl.vhd
- LCLS-II/core/rtl/EventSelect.vhd
- LCLS-II/core/rtl/GthRxAlignCheck.vhd
- LCLS-II/core/rtl/TPGMini.vhd
- LCLS-II/core/rtl/TPGNotify.vhd
- LCLS-II/core/rtl/TPGPkg.vhd
- LCLS-II/core/rtl/TimingCore.vhd
- LCLS-II/core/rtl/TimingFrameRx.vhd
- LCLS-II/core/rtl/TimingMsgDelay.vhd
- LCLS-II/core/rtl/TimingPkg.vhd
- LCLS-II/core/rtl/TimingRx.vhd
- LCLS-II/core/rtl/TimingSerialDelay.vhd
- LCLS-II/core/rtl/TimingStreamRx.vhd
- LCLS-II/core/tb/TimingSerialDelay_tb.vhd
- LCLS-II/evr/rtl/EvrV2CorePulseGen.vhd
- LCLS-II/evr/rtl/EvrV2EventSelect.vhd
- LCLS-II/evr/rtl/EvrV2FromV1.vhd
- LCLS-II/evr/rtl/EvrV2Trigger.vhd
- LCLS-II/gthUltraScale/ruckus.tcl
- LCLS-II/gtx7/rtl/TimingGtCoreWrapper.vhd
- LCLS-II/gtx7/ruckus.tcl
- LCLS-II/ruckus.tcl
- LICENSE.txt
- ruckus.tcl
- Revamp Extension Bus Interface #78
- Updated LICENSE.txt for year 2020
- LCLS-I/evr/EvrV1CoreIsrCtrl.vhd bug fix #91
- TimingMsgDelay.vhd bug fix #92
- Use EXPT_STREAM_ID for secondary stream identifier #83
- adding gtx7/TimingGtCoreWrapper #95
> Release Candidate v3.0.0

- LCLS-II/gtx7/rtl/TimingGtCoreWrapper.vhd
Added an option for external IBUFDS_GTE2. Fixed a VCS compile error.
> TimingGtCoreWrapper with external ref clock buffer

- .travis.yml
- python/LclsTimingCore/EvrV1Isr.py
- python/LclsTimingCore/EvrV1Reg.py
- python/LclsTimingCore/EvrV2ChannelReg.py
- python/LclsTimingCore/EvrV2Core.py
- python/LclsTimingCore/EvrV2CoreTriggers.py
- python/LclsTimingCore/EvrV2TriggerReg.py
- python/LclsTimingCore/GthRxAlignCheck.py
- python/LclsTimingCore/LclsTriggerPulse.py
- python/LclsTimingCore/TPG.py
- python/LclsTimingCore/TPGControl.py
- python/LclsTimingCore/TPGMiniCore.py
- python/LclsTimingCore/TPGSeqJump.py
- python/LclsTimingCore/TPGSeqState.py
- python/LclsTimingCore/TPGStatus.py
- python/LclsTimingCore/TimingFrameRx.py
- python/LclsTimingCore/__init__.py
- releaseNotes.py
- tox.ini
- Added python linter to travic CI
- Fixed some bugs in the python code
- Caught by the linter
- Some mics code header clean up
> adding flake8 to .travis.yml

- LCLS-II/core/rtl/TimingRx.vhd
- LCLS-II/core/rtl/TimingSerialDelay.vhd
- LCLS-II/evr/rtl/EvrV2CoreTriggers.vhd
- LCLS-II/evr/rtl/EvrV2TriggerCompl.vhd
- python/LclsTimingCore/EvrV2TriggerReg.py
- python/LclsTimingCore/TimingFrameRx.py
- yaml/EvrV2TriggerReg.yaml
Fix for the odd number of triggers plus other commits I missed earlier.
Also clean up `python/LclsTimingCore/TimingFrameRx.py` a bit.
> Bug Fix for Complementary Trigger Feature

- LCLS-II/core/rtl/TimingCore.vhd
- LCLS-II/core/rtl/TimingRx.vhd
- LCLS-II/core/rtl/TimingSerialDelay.vhd
- LCLS-II/evr/rtl/EvrV2CoreTriggers.vhd
- LCLS-II/evr/rtl/EvrV2TriggerCompl.vhd
- updating TimingRx's AXI-Lite reset procedure
- which was previously commented out (by accident???)
- Whitespace Removal
> TimingRx Reset Update and Whitespace Removal

- LCLS-I/evr/EvrV1Reg.vhd
- LCLS-II/core/rtl/TimingRx.vhd
- ruckus.tcl
- axilReadSlave.rdata needs to be reset to zero inside axiSlaveWaitTxn to prevent AXI-Lite protocol violation
- https://github.com/slaclab/surf/pull/718
> Surf v2.8.0 update

- LCLS-I/evr/EvrV1Reg.vhd
- LCLS-II/core/rtl/TimingCore.vhd
- LCLS-II/core/rtl/TimingRx.vhd
- LCLS-II/core/rtl/TimingSerialDelay.vhd
- LCLS-II/evr/rtl/EvrV2CoreTriggers.vhd
- LCLS-II/evr/rtl/EvrV2Pkg.vhd
- LCLS-II/evr/rtl/EvrV2TriggerCompl.vhd
- python/LclsTimingCore/TimingFrameRx.py
- ruckus.tcl
- TimingFrameRx.py Bug Fix and TimingCore.vhd Update #119
- Surf v2.8.0 update #120
- updating EvrV2Pkg.EVRV2_TRIGGER_CONFIG_INIT_C.width default from 0x0 to 0x1 #121
> v3.2.2 release candidate

- LCLS-I/evr/EvrV1EventReceiver.vhd
- Remove prescaler reset from LCLS-I evr trigger logic #123
> v3.2.3 release candidate

- LCLS-II/evr/rtl/EvrV2CoreTriggers.vhd
- LCLS-II/evr/rtl/EvrV2TriggerCompl.vhd
Fix whitespace and add TPD_G waits in a few modules.
> Small code cleanup

- LCLS-II/core/rtl/TPGPkg.vhd
- LCLS-II/evr/rtl/EvrV2CoreTriggers.vhd
- LCLS-II/evr/rtl/EvrV2TriggerCompl.vhd
- Small code cleanup #128
- Add beam charge override field to TPG #127
>  v3.3.0 release candidate

- LCLS-II/gtp7/rtl/TimingGtCoreWrapper.vhd
- LCLS-II/gtp7/ruckus.tcl
- LCLS-II/ruckus.tcl
- adding GTP7 support to LCLS-II's TimingGtCoreWrapper.vhd #130
> v3.4.0 release candidate

- yaml/GthRxAlignCheck.yaml
- adding missing GthRxAlignCheck's TxClkFreq and RxClkFreq registers
> v3.4.1 release candidate

- LCLS-II/core/rtl/BsaControlv2.vhd
- LCLS-II/core/rtl/TPGMini.vhd
> Release Candidate v3.6.4

- LCLS-II/core/rtl/TPGMini.vhd
- LCLS-II/core/rtl/TPGPkg.vhd
Increase some feature parameters for TPG.
> V3.6.4 maxseq

- LCLS-II/core/rtl/TPGMini.vhd
- LCLS-II/core/rtl/TPGPkg.vhd
> Release Candidate v3.6.5

- .github/workflows/timing_ci.yml
- LICENSE.txt
- setup.py
- [Bug fix for conda build](https://github.com/slaclab/lcls-timing-core/commit/f3dcf5615ec0cea3b40675fe0f62a125d1c6aa35)
- [Update LICENSE.txt](https://github.com/slaclab/lcls-timing-core/commit/0d1f4ef287c96229823fea40616c07917fad1236)
> Release Candidate v3.7.1

- .github/workflows/timing_ci.yml
- LCLS-II/gtyUltraScale+/rtl/TimingGtCoreWrapper.vhd
- [Update timing_ci.yml](https://github.com/slaclab/lcls-timing-core/commit/24115931dca1ea666d8e57a4ac5b384ad2086aa2)
- [Use Gtye4ChannelDummy in gtyUltrascale+ core wrapper](https://github.com/slaclab/lcls-timing-core/commit/9506f731fe66cad37aad2ab8bac018666c59c009)
> Release Candidate v3.7.2

- LCLS-II/core/rtl/TimingFrameRx.vhd
- LCLS-II/core/rtl/TimingRx.vhd
- LCLS-II/core/rtl/TimingSerialDelay.vhd
- LCLS-II/evr/rtl/EvrV2Trigger.vhd
> Release Candidate v3.7.3

- LCLS-II/gtyUltraScale+/coregen/smurf/TimingGty_fixedlat.dcp
- LCLS-II/gtyUltraScale+/coregen/smurf/TimingGty_fixedlat.xci
- adding cpllrefclksel_in & gtgrefclk_in ports to match LCLS-II API
> Updating smurf/TimingGty_fixedlat.[xci,dcp]

- LCLS-II/core/rtl/GthRxAlignCheck.vhd
- LCLS-II/core/rtl/TimingDeserializer.vhd
- LCLS-II/core/rtl/TimingFrameRx.vhd
- LCLS-II/core/rtl/TimingRx.vhd
- LCLS-II/gthUltraScale+/coregen/TimingGth_extref.dcp
- LCLS-II/gthUltraScale+/coregen/TimingGth_extref.xci
- LCLS-II/gthUltraScale+/coregen/TimingGth_fixedlat.dcp
- LCLS-II/gthUltraScale+/coregen/TimingGth_fixedlat.xci
- LCLS-II/gthUltraScale+/rtl/TimingGthCoreWrapper.vhd
- LCLS-II/gthUltraScale+/ruckus.tcl
- LICENSE.txt
- python/LclsTimingCore/GthRxAlignCheck.py
- #162 
- [Added some keep attributes and mask register](https://github.com/slaclab/lcls-timing-core/commit/216ae8eb04bff011f7fc18a45e7e1e16e972b602)
- [Update LICENSE.txt for 2024](https://github.com/slaclab/lcls-timing-core/commit/09aaa33fc998a321a819a0a575e96ef912f786a4)
> Release Candidate v3.8.0

- LCLS-II/evr/rtl/EvrV2Trigger.vhd
- https://github.com/slaclab/lcls-timing-core/pull/176 recreated a bug where no triggers generated when TRIG_DEPTH_C=0
- Remove NO_FIFO implementation from EvrV2Trigger; its always needed.
> Bug fix for LCLS-II/evr/rtl/EvrV2Trigger.vhd

- .github/workflows/timing_ci.yml
- LCLS-I/ruckus.tcl
- LCLS-II/core/ruckus.tcl
- LCLS-II/evr/rtl/EvrV2Trigger.vhd
- LCLS-II/evr/ruckus.tcl
- LCLS-II/gthUltraScale+/ruckus.tcl
- LCLS-II/gthUltraScale/rtl/TimingGtCoreWrapper.vhd
- LCLS-II/gthUltraScale/ruckus.tcl
- LCLS-II/gtp7/ruckus.tcl
- LCLS-II/gtx7/ruckus.tcl
- LCLS-II/gtyUltraScale+/rtl/TimingGtCoreWrapper.vhd
- LCLS-II/gtyUltraScale+/ruckus.tcl
- LCLS-II/ruckus.tcl
- README.md
- ruckus.tcl
- [whitespace removal](https://github.com/slaclab/lcls-timing-core/commit/65ae158bfe17c75537cea6a248ea280832a58726)
- [migrating CI from ubuntu-22.04 to ubuntu-24.04](https://github.com/slaclab/lcls-timing-core/commit/1202604b935dee4538f280adb26fe8d383d11668)
- [emac VHDL clean up](https://github.com/slaclab/lcls-timing-core/commit/383828a34d1ad8fdb7ab4cf5f2150100a1811fb4)
- [Update README.md to include DOE Code Reference](https://github.com/slaclab/lcls-timing-core/pull/182/commits/48e90a9a346ff32efc992bbfd2e6ca233d5d43fe)
> Release Candidate v3.10.1

- LCLS-II/core/rtl/TimingSerialDelay.vhd
- [whitepace removal](https://github.com/slaclab/lcls-timing-core/commit/617f00f7527b135fd35ea0b28f3dc3827b46a2d2)
> Release Candidate v3.10.4
